config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/inventory_items', to: 'inventory_items#index'
  resources :inventory_items
  resources :locations
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory_item.rb
# frozen_string_literal: true

class InventoryItem < ApplicationRecord
  validates :name, presence: true
  validates :unit_price, presence: true

  has_many :location_inventories
  has_many :locations, through: :location_inventories

  def self.to_csv
    attributes = %w[id name description unit_price created_at updated_at]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |item|
        csv << item.attributes.values_at(*attributes)
      end
    end
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  validates :name, presence: true

  has_many :location_inventories
  has_many :inventory_items, through: :location_inventories
end

app/models/location_inventory.rb
# frozen_string_literal: true

class LocationInventory < ApplicationRecord
  belongs_to :inventory_item
  belongs_to :location
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/inventory_items_controller.rb
# frozen_string_literal: true

class InventoryItemsController < ApplicationController
  def index
    @inventory_items = InventoryItem.all

    respond_to do |format|
      format.html
      format.csv { send_data @inventory_items.to_csv }
    end
  end

  def show
    @inventory_item = InventoryItem.find(params[:id])
  end

  def new
    @inventory_item = InventoryItem.new
  end

  def create
    inventory_item = InventoryItem.new(items_params)
    inventory_item.save
    redirect_to inventory_items_path
  end

  def edit
    @inventory_item = InventoryItem.find(params[:id])
  end

  def update
    item = InventoryItem.find(params[:id])
    item.update(items_params)
    item.save

    redirect_to inventory_item_path
  end

  def destroy
    item = InventoryItem.find(params[:id])
    item.destroy
    redirect_to inventory_items_path
  end

  private

  def items_params
    params.permit(:name, :description, :unit_price)
  end
end

app/controllers/locations_controller.rb
# frozen_string_literal: true

class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @locations = Location.new
  end

  def create
    location = Location.new(location_params)
    location.save
    redirect_to locations_path
  end

  def show
    @location = Location.find(params[:id])
    @inventory_items = InventoryItem.all
  end

  private

  def location_params
    params.permit(:name, :description, :inventory_item_ids)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/inventory_items/edit.html.erb
<h1>Edit <%= @inventory_item.name %></h1>
<br>
<%= form_with url: "/inventory_items/#{@inventory_item.id}", method: :patch, local: true do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, value: "#{@inventory_item.name}" %><br><br>
  <%= f.label :description, "Description" %>
  <%= f.text_field :description, value: "#{@inventory_item.description}" %><br><br>
  <%= f.label :unit_price, "Unit Price" %>
  <%= f.text_field :unit_price, value: "#{@inventory_item.unit_price}" %><br><br>
  <%= f.submit %>
<% end %>

app/views/inventory_items/index.html.erb
<h1>Inventory Items</h1>
<% @inventory_items.each do |items| %>
  <h3> Name: </h3><%= link_to items.name, inventory_item_path(items.id) %><br>
  <h3> Description: </h3><%= items.description %><br>
  <h3> Unit Price: </h3><%= number_to_currency(items.unit_price) %><br>
  <%= button_to "Update #{items.name}", edit_inventory_item_path(items.id), method: :get %><br>
  <%= button_to "Delete #{items.name}", "/inventory_items/#{items.id}", method: :delete %>
<% end %>
<br>
<%= link_to 'Create a new inventory item', new_inventory_item_path %><br><br>
<a href="/inventory_items.csv"><button class="btn btn-success">export all</button></a>

app/views/inventory_items/new.html.erb
<h1>Create a New Inventory Item</h1>
<br>
<%= form_with url: inventory_items_path, method: :post, local: true do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field(:name) %><br><br>
  <%= f.label :description, "Description" %>
  <%= f.text_field(:description) %><br><br>
  <%= f.label :unit_price, "Unit Price" %>
  <%= f.text_field(:unit_price) %><br><br>
  <%= f.submit %>
<% end %>

app/views/inventory_items/show.html.erb
<h1><%= @inventory_item.name %></h1>
<br>
<p>
  Description <%= @inventory_item.description %>
</p><br>
<p>
  Unit Price <%= number_to_currency(@inventory_item.unit_price) %>
</p>

<%= link_to 'Full Inventory List', inventory_items_path %>
<%= button_to 'Update', edit_inventory_item_path(@inventory_item.id), method: :get %>
<%= button_to "Delete #{@inventory_item.name}", "/inventory_items/#{@inventory_item.id}", method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SummerInternship</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Locations</h1>
<% @locations.each do |location| %>
  <h3> Name: </h3><%= link_to location.name, location_path(location.id) %><br>
  <p> Description: <p><%= location.description %>
<% end %>
<br>
<%= link_to 'Create a new Location', new_location_path %><br><br>

app/views/locations/new.html.erb
<h1>Create a New Location</h1>
<br>
<%= form_with url: locations_path, method: :post, local: true do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field(:name) %><br><br>
  <%= f.label :description, "Description" %>
  <%= f.text_field(:description) %><br><br>
  <%= f.collection_check_boxes :inventory_item_ids, InventoryItem.all, :id, :name, {hide_label: true} %><br><br>
  <%= f.submit %>
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<h1><%= @location.description %></h1>
<h1><%= @inventory_items.name %></h1>
<br>

<%= link_to 'Add Inventory', inventory_items_path %>

<%= link_to 'All locations', locations_path %>